name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}

env:
  ZIG_VERSION: 0.15.1

jobs:
  # Quick validation checks that should pass before any other jobs
  validation:
    name: Validation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Zig
        uses: ./.github/actions/setup-zig

      - name: Check Formatting
        run: ./zig/zig build fmt-check

      - name: Check Style Rules
        run: ./zig/zig build tidy

      - name: Validate Build Configuration
        run: ./zig/zig build --help > /dev/null

  # Main test matrix with deterministic seeds
  test-matrix:
    name: Test / ${{ matrix.os }} / seed:${{ matrix.seed }}
    needs: validation
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        seed:
          - "0xDEADBEEF"
          - "0xCAFEBABE"
          - "0x8BADF00D"
          - "0xFEEDFACE"
          - "0x1337BEEF"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Zig
        uses: ./.github/actions/setup-zig

      - name: Cache Build Artifacts
        uses: actions/cache@v4
        with:
          path: |
            zig-cache
            zig-out
          key: ${{ runner.os }}-zig-${{ hashFiles('build.zig', 'src/**/*.zig') }}-${{ matrix.seed }}
          restore-keys: |
            ${{ runner.os }}-zig-${{ hashFiles('build.zig', 'src/**/*.zig') }}-
            ${{ runner.os }}-zig-

      - name: Run Unit Tests
        run: |
          echo "========================================="
          echo "Testing on ${{ matrix.os }} with seed: ${{ matrix.seed }}"
          echo "Reproduce failures with: ./zig/zig build test-unit -Dseed=${{ matrix.seed }}"
          echo "========================================="
          ./zig/zig build test-unit -Dseed=${{ matrix.seed }} -Dtest-iterations=3

      - name: Run Integration Tests
        run: ./zig/zig build test-integration -Dseed=${{ matrix.seed }}

      - name: Run E2E Tests
        run: ./zig/zig build test-e2e -Dseed=${{ matrix.seed }}

      - name: Upload Test Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-${{ matrix.os }}-${{ matrix.seed }}
          path: |
            zig-out/
            test-logs/
          retention-days: 7

  # Valgrind memory analysis (separate job due to significant slowdown)
  valgrind:
    name: Valgrind Analysis
    needs: validation
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Zig
        uses: ./.github/actions/setup-zig

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Build
        run: ./zig/zig build -Doptimize=Debug -Dseed=0xDEADBEEF

      - name: Run Valgrind Memory Check
        run: |
          valgrind \
            --tool=memcheck \
            --leak-check=full \
            --show-leak-kinds=all \
            --track-origins=yes \
            --error-exitcode=1 \
            --gen-suppressions=all \
            --log-file=valgrind-report.txt \
            --read-var-info=no \
            --quiet \
            ./zig-out/bin/test

      - name: Upload Valgrind Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: valgrind-report
          path: valgrind-report.txt
          retention-days: 7

  # Performance benchmarking and regression detection
  benchmarks:
    name: Benchmarks
    needs: validation
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for baseline comparison

      - name: Setup Zig
        uses: ./.github/actions/setup-zig

      - name: Download Previous Benchmark Results
        uses: actions/cache@v4
        with:
          path: bench-baseline.json
          key: benchmarks-${{ runner.os }}-${{ github.base_ref || 'main' }}
          restore-keys: |
            benchmarks-${{ runner.os }}-

      - name: Run Benchmarks
        run: |
          ./zig/zig build bench \
            -Doptimize=ReleaseFast \
            -Dbench-iterations=10000 \
            -Dbench-warmup=1000 \
            -Dbench-baseline=bench-baseline.json \
            > bench-results.txt 2>&1

      - name: Check for Performance Regressions
        run: |
          # Parse benchmark results and check for regressions
          if grep -q "REGRESSION" bench-results.txt; then
            echo "::error::Performance regression detected!"
            cat bench-results.txt
            exit 1
          fi

      - name: Save Benchmark Results
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          # Save benchmark results as baseline for comparison
          cp bench-results.txt bench-baseline.json || true

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: bench-results.txt
          retention-days: 30

      - name: Comment PR with Benchmark Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('bench-results.txt', 'utf8');
            const summary = results.split('\n').filter(line =>
              line.includes('avg') || line.includes('PASS') || line.includes('REGRESSION')
            ).join('\n');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Benchmark Results\n\`\`\`\n${summary}\n\`\`\``
            });

  # Fuzzing for bug discovery
  fuzzing:
    name: Fuzzing
    needs: validation
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Zig
        uses: ./.github/actions/setup-zig

      - name: Restore Fuzz Corpus
        uses: actions/cache@v4
        with:
          path: fuzz-corpus
          # Use source hash + date to create evolving corpus cache
          key: fuzz-corpus-${{ hashFiles('src/**/*.zig') }}-${{ github.run_number }}
          restore-keys: |
            fuzz-corpus-${{ hashFiles('src/**/*.zig') }}-
            fuzz-corpus-

      - name: Run Quick Fuzz Test
        run: |
          ./zig/zig build fuzz-quick \
            -Dfuzz-corpus=fuzz-corpus

      - name: Run Extended Fuzzing (main branch only)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          ./zig/zig build fuzz \
            -Dfuzz-iterations=100000 \
            -Dfuzz-corpus=fuzz-corpus

      - name: Save Corpus Statistics
        if: success() || failure()
        run: |
          echo "Fuzzing corpus statistics:"
          find fuzz-corpus -type f -name "*.bin" | wc -l || echo "0"
          du -sh fuzz-corpus/ || echo "0B"

      - name: Upload Crash Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-crashes
          path: |
            fuzz-corpus/crashes/
            fuzz-corpus/hangs/
          retention-days: 30

  # Release build verification
  release:
    name: Release Build / ${{ matrix.os }}
    needs: [test-matrix]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Zig
        uses: ./.github/actions/setup-zig

      - name: Build Release Binary
        run: |
          ./zig/zig build \
            -Doptimize=ReleaseSafe \
            -Dtarget=${{ matrix.os == 'ubuntu-latest' && 'x86_64-linux' || 'x86_64-macos' }}

      - name: Test Release Binary
        run: |
          ./zig-out/bin/kausaldb --version
          ./zig-out/bin/kausaldb --help

      - name: Package Release
        run: |
          tar -czf kausaldb-${{ matrix.os }}.tar.gz -C zig-out/bin kausaldb

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: kausaldb-${{ matrix.os }}.tar.gz
          retention-days: 30

  # Final status check
  ci-status:
    name: CI Status
    needs: [validation, test-matrix, benchmarks, fuzzing, release]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check CI Status
        if: |
          needs.validation.result != 'success' ||
          needs.test-matrix.result != 'success' ||
          needs.benchmarks.result != 'success' ||
          needs.fuzzing.result != 'success' ||
          needs.release.result != 'success'
        run: |
          echo "::error::CI pipeline failed"
          exit 1

      - name: CI Success
        if: success()
        run: echo "CI pipeline passed successfully"
