name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Extract Zig version
        id: zig-version
        run: |
          ZIG_VERSION=$(grep 'ZIG_RELEASE_DEFAULT=' scripts/install-zig.sh | sed 's/.*="\([^"]*\)".*/\1/')
          echo "version=$ZIG_VERSION" >> $GITHUB_OUTPUT
          echo "Extracted Zig version: $ZIG_VERSION"

      - name: Setup Zig
        run: |
          chmod +x scripts/install-zig.sh
          ./scripts/install-zig.sh
          echo "Using Zig: $(./zig/zig version)"

      - name: Cache Zig artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/zig
            zig-cache
            zig-out
          key: ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-${{ hashFiles('build.zig', 'build.zig.zon') }}-test
          restore-keys: |
            ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-${{ hashFiles('build.zig', 'build.zig.zon') }}-
            ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-

      - name: Check formatting
        run: ./zig/zig fmt --check .

      - name: Build debug
        run: ./zig/zig build

      - name: Run tests
        run: ./zig/zig build test

      - name: Run tidy checks
        run: ./zig/zig build tidy

      - name: Build all targets
        run: |
          echo "-> Building benchmark target..."
          ./zig/zig build benchmark
          echo "-> Building fuzz target..."
          ./zig/zig build fuzz

      - name: Build release
        run: ./zig/zig build --release=safe

  build-matrix:
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Extract Zig version
        id: zig-version
        shell: bash
        run: |
          ZIG_VERSION=$(grep 'ZIG_RELEASE_DEFAULT=' scripts/install-zig.sh | sed 's/.*="\([^"]*\)".*/\1/')
          echo "version=$ZIG_VERSION" >> $GITHUB_OUTPUT
          echo "Extracted Zig version: $ZIG_VERSION"

      - name: Setup Zig
        shell: bash
        run: |
          chmod +x scripts/install-zig.sh
          ./scripts/install-zig.sh
          echo "Using Zig: $(./zig/zig version)"

      - name: Cache Zig artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/zig
            zig-cache
            zig-out
          key: ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-${{ hashFiles('build.zig', 'build.zig.zon') }}-build
          restore-keys: |
            ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-${{ hashFiles('build.zig', 'build.zig.zon') }}-
            ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-

      - name: Validate build system
        shell: bash
        run: |
          echo "-> Validating build on ${{ matrix.os }}..."
          ./zig/zig build --help

      - name: Build release
        shell: bash
        run: ./zig/zig build --release=safe

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Extract Zig version
        id: zig-version
        run: |
          ZIG_VERSION=$(grep 'ZIG_RELEASE_DEFAULT=' scripts/install-zig.sh | sed 's/.*="\([^"]*\)".*/\1/')
          echo "version=$ZIG_VERSION" >> $GITHUB_OUTPUT
          echo "Extracted Zig version: $ZIG_VERSION"

      - name: Setup Zig
        run: |
          chmod +x scripts/install-zig.sh
          ./scripts/install-zig.sh
          echo "Using Zig: $(./zig/zig version)"

      - name: Cache Zig artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/zig
            zig-cache
            zig-out
          key: ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-${{ hashFiles('build.zig', 'build.zig.zon') }}-coverage
          restore-keys: |
            ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-${{ hashFiles('build.zig', 'build.zig.zon') }}-

      - name: Generate coverage
        run: ./zig/zig build test -- --summary all

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Extract Zig version
        id: zig-version
        run: |
          ZIG_VERSION=$(grep 'ZIG_RELEASE_DEFAULT=' scripts/install-zig.sh | sed 's/.*="\([^"]*\)".*/\1/')
          echo "version=$ZIG_VERSION" >> $GITHUB_OUTPUT
          echo "Extracted Zig version: $ZIG_VERSION"

      - name: Setup Zig
        run: |
          chmod +x scripts/install-zig.sh
          ./scripts/install-zig.sh
          echo "Using Zig: $(./zig/zig version)"

      - name: Check for banned patterns
        run: |
          echo "-> Checking for banned patterns..."
          if grep -r "std\.BoundedArray" src/; then
            echo "Error: Found banned pattern std.BoundedArray"
            exit 1
          fi
          if grep -r "std\.StaticBitSet" src/; then
            echo "Error: Found banned pattern std.StaticBitSet"
            exit 1
          fi
          if grep -r "FIXME\|TODO" src/ --include="*.zig"; then
            echo "Warning: Found FIXME/TODO comments in source"
          fi

      - name: Check commit message format
        if: github.event_name == 'pull_request'
        run: |
          echo "-> Checking PR title format..."
          if ! echo "${{ github.event.pull_request.title }}" | grep -E '^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+'; then
            echo "Warning: PR title doesn't follow conventional commit format"
          fi

  security:
    name: Security
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Check for secrets
        run: |
          echo "-> Scanning for potential secrets..."
          if grep -r -i "password\|secret\|key\|token" src/ --include="*.zig" | grep -v "// "; then
            echo "Warning: Potential hardcoded secrets found"
          fi

      - name: Check file permissions
        run: |
          echo "-> Checking file permissions..."
          find . -type f -perm /111 -name "*.zig" | while read file; do
            echo "Warning: Executable Zig source file: $file"
          done

      - name: Validate project structure
        run: |
          echo "-> Validating project structure..."
          if [ ! -f "build.zig" ]; then
            echo "Error: Missing build.zig"
            exit 1
          fi
          if [ ! -f "build.zig.zon" ]; then
            echo "Error: Missing build.zig.zon"
            exit 1
          fi
          if [ ! -d "src" ]; then
            echo "Error: Missing src directory"
            exit 1
          fi

  performance:
    name: Performance Regression Detection
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for baseline comparison

      - name: Extract Zig version
        id: zig-version
        run: |
          ZIG_VERSION=$(grep 'ZIG_RELEASE_DEFAULT=' scripts/install-zig.sh | sed 's/.*="\([^"]*\)".*/\1/')
          echo "version=$ZIG_VERSION" >> $GITHUB_OUTPUT
          echo "Extracted Zig version: $ZIG_VERSION"

      - name: Setup Zig
        run: |
          chmod +x scripts/install-zig.sh
          ./scripts/install-zig.sh
          echo "Using Zig: $(./zig/zig version)"

      - name: Cache Zig artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/zig
            zig-cache
            zig-out
          key: ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-${{ hashFiles('build.zig', 'build.zig.zon') }}-perf
          restore-keys: |
            ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-${{ hashFiles('build.zig', 'build.zig.zon') }}-
            ${{ runner.os }}-zig-${{ steps.zig-version.outputs.version }}-

      - name: Run performance regression detection
        run: |
          chmod +x scripts/performance-ci.sh
          ./scripts/performance-ci.sh

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-results
          path: |
            .github/performance-baseline.json
            /tmp/current-performance.json
          retention-days: 30

      - name: Comment performance results on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = '.github/performance-baseline.json';
            
            if (fs.existsSync(path)) {
              const baseline = JSON.parse(fs.readFileSync(path, 'utf8'));
              const comment = `## Performance Report
              
              Performance benchmarks completed successfully!
              
              **Benchmark Categories:** Storage, Query, Compaction
              **Regression Threshold:** 15% slowdown
              **Status:** All operations within acceptable bounds
              
              See [performance-results artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for detailed metrics.
              `;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
